"use client";

import * as React from "react";
import { GlassCard, GlassBadge, GlassButton, Spinner, useToast } from "@/components/ui/glass";
import { apiGet } from "@/lib/http";

interface AICard {
  id: string;
  type: string;
  title: string;
  description: string;
  priority: "high" | "medium" | "low";
  domain: string;
  createdAt: string;
  actions: Array<{
    label: string;
    type: "navigate" | "create_task" | "dismiss" | "snooze";
    href?: string;
  }>;
}

interface AICardsResponse {
  items: AICard[];
}

const PRIORITY_VARIANTS: Record<string, "danger" | "warning" | "default"> = {
  high: "danger",
  medium: "warning",
  low: "default",
};

export function AITasksTab() {
  const { addToast } = useToast();
  const [cards, setCards] = React.useState<AICard[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [dismissed, setDismissed] = React.useState<Set<string>>(new Set());

  React.useEffect(() => {
    async function loadData() {
      try {
        const data = await apiGet<AICardsResponse>("/api/ai/cards?domain=sales-customers");
        setCards(data.items || []);
      } catch {
        setCards([]);
      } finally {
        setLoading(false);
      }
    }
    loadData();

    // Load dismissed from localStorage
    try {
      const savedDismissed = localStorage.getItem("udp-ai-tasks-dismissed");
      if (savedDismissed) {
        setDismissed(new Set(JSON.parse(savedDismissed)));
      }
    } catch {
      // Ignore
    }
  }, []);

  const handleDismiss = (cardId: string) => {
    const newDismissed = new Set(dismissed);
    newDismissed.add(cardId);
    setDismissed(newDismissed);
    localStorage.setItem("udp-ai-tasks-dismissed", JSON.stringify([...newDismissed]));
    addToast("success", "Task dismissed");
  };

  const handleAction = (card: AICard, action: AICard["actions"][0]) => {
    if (action.type === "dismiss") {
      handleDismiss(card.id);
    } else if (action.type === "navigate" && action.href) {
      window.location.href = action.href;
    } else if (action.type === "create_task") {
      addToast("info", "Task creation coming soon");
    } else if (action.type === "snooze") {
      handleDismiss(card.id);
      addToast("success", "Task snoozed for 24 hours");
    }
  };

  const visibleCards = cards.filter((c) => !dismissed.has(c.id));

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Spinner size="lg" />
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Info Card */}
      <GlassCard padding="sm">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-purple-500/20">
            <svg className="w-5 h-5 text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
            </svg>
          </div>
          <div>
            <h3 className="text-sm font-medium text-white">AI Suggestions</h3>
            <p className="text-xs text-white/50">Tasks and recommendations generated by AI to help you manage sales and customers.</p>
          </div>
        </div>
      </GlassCard>

      {/* Task Cards */}
      {visibleCards.length > 0 ? (
        <div className="grid gap-4">
          {visibleCards.map((card) => (
            <GlassCard key={card.id}>
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-2">
                    <h3 className="font-semibold text-white">{card.title}</h3>
                    <GlassBadge variant={PRIORITY_VARIANTS[card.priority]}>
                      {card.priority}
                    </GlassBadge>
                    <span className="text-xs text-white/40 bg-white/5 px-2 py-0.5 rounded">
                      {card.type.replace("_", " ")}
                    </span>
                  </div>
                  <p className="text-sm text-white/70 mb-4">{card.description}</p>
                  <div className="flex flex-wrap gap-2">
                    {card.actions.map((action, idx) => (
                      <GlassButton
                        key={idx}
                        size="sm"
                        variant={action.type === "dismiss" || action.type === "snooze" ? "ghost" : "primary"}
                        onClick={() => handleAction(card, action)}
                      >
                        {action.label}
                      </GlassButton>
                    ))}
                  </div>
                </div>
              </div>
            </GlassCard>
          ))}
        </div>
      ) : (
        <GlassCard>
          <div className="text-center py-12">
            <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-emerald-500/20 flex items-center justify-center">
              <svg className="w-8 h-8 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <h3 className="text-lg font-semibold text-white mb-2">All Caught Up!</h3>
            <p className="text-white/50">
              No AI suggestions at the moment. Check back later for new recommendations.
            </p>
          </div>
        </GlassCard>
      )}
    </div>
  );
}
